name: poetsd8
proxy:
  appserver:
    - poetsd8.lndo.site:3000
excludes:
  - node_modules
env_file:
  - .env
services:
  appserver:
    type: node:10
    command: cp -n /app/.env.example /app/.env && yarn dev --hostname 0.0.0.0
    port: 3000
    build:
      - yarn install
tooling:
  yarn:
    service: appserver
  npm:
    service: appserver
  node:
    service: appserver
  nuxt:
    cmd: /app/node_modules/.bin/nuxt
    service: appserver
  test:
    cmd: yarn test
    service: codeception
  codecept:
    cmd: /app/node_modules/.bin/codeceptjs
    service: appserver
