name: poetsd8
proxy:
  appserver:
    - poetsd8.lndo.site
services:
  appserver:
    type: node:10
    command: cp -n /app/.env.example /app/.env && yarn dev --hostname 0.0.0.0 --port 80 --max-old-space-size=8192
    install_dependencies_as_me:
      - yarn install
  codeception:
    type: compose
    services:
      image: codeception/codeceptjs
      command: /codecept/docker/entrypoint
tooling:
  yarn:
    service: appserver
  npm:
    service: appserver
  node:
    service: appserver
  nuxt:
    cmd: /app/node_modules/.bin/nuxt
    service: appserver
  test:
    cmd: yarn test
    service: codeception
