# App and type
name: app
type: nodejs:12

# Dependencies
dependencies:
  nodejs:
    pm2: "3.5.0"
    yarn: latest

# Disk and mounts
disk: 4000
mounts:
  run:
    source: local
    source_path: run
  '/tmp': 'shared:files/tmp'

variables:
  env:
    NODE_OPTIONS: --max_old_space_size=1536

# Boot up
web:
  commands:
    start: "PM2_HOME=/app/run pm2 start ecosystem.config.js --no-daemon"

# Hooks
hooks:
  build: |
    # We need the below otherwise only the exit code of the last command
    # is used to determine the status of the entire build
    # See: https://docs.platform.sh/configuration/app/build.html#hooks
    set -e
    # Build
    yarn install
    API_URL=https://pr-992-n425ktq-iw4bgahutfk2y.us-2.platformsh.site yarn build
    # We need to do the below manually for now
    # See: https://github.com/yarnpkg/yarn/issues/6685
    yarn cache clean
    rm -rf /tmp/yarn--*

# crons
crons:
  sitemap:
    spec: '22 2 1,15 * *'
    cmd: 'curl -I https://poets.org/sitemap.xml'
  submitSitemap:
    spec: '0 1 * * *'
    cmd: 'curl -I https://poets.org/submit-sitemap'
